### ISSUE TITLE
[API V1][상세페이지] 초기 리뷰 DTO 수정 

### ISSUE THREAD

**Issue by dionisos198** [TAVE-balak/OTTify-backend#111]
## 🔥 Issue
처음 4개의 리뷰를 보여주면서 남은 리뷰의 개수를 같은 DTO 에 묶어서 보내는 등 여러가지 DTO 를 수정하고 
헷갈릴만한 swagger 세팅을 제거한다. 

## ✅ TODO
- [x]  4개의 리뷰를 보여주며 남은 리뷰의 개수도 DTO 로 보내기
- [x]  UserGenreRating을 소숫점 첫재짜리 까지 보여주는 것으로 수정
- [x]  헷갈릴만한 swagger 세팅 제거 
- [x]  Users의 선호장르별 평점을 보여주는 기능을 기존 리뷰 show Controller 에서 ProgramDetailController로 옮김
- [x] API 경로를 조금더 직관적이게 수정
