### ISSUE TITLE
[API V1][마이페이지] 프로필 수정 로직 변경

### ISSUE THREAD

**Issue by jyjyjy25** [TAVE-balak/OTTify-backend#117]
#### 1. 프로필 수정 시 프로필 사진 필수 여부에 대한 로직 변경
현재 프로필 수정 시 프로필 사진은 필수로 보내야 하는 값이 아니다.
하지만 현재 서비스 코드 내에 프로필 사진 값의 존재 여부를 확인하는 코드는 다음과 같다.
`if (!updateRequestDTO.getProfilePhoto().isEmpty()) {}`
- **isEmpty()**: MultipartFile이 비어있는지를 확인합니다. 파일이 비어있다는 것은 파일이 선택되었지만 내용이 없거나, 파일 크기가 0이라는 것을 의미합니다. 따라서 이를 통해 프로필 사진이 전송되었지만 내용이 없는 경우를 체크하는 함수입니다.

이 경우 요청을 보낼 때 아래와 같이 profilePhoto에 빈 값이라도 보내줘야 한다.
<img width="1008" alt="image" src="https://github.com/TAVE-balak/OTTify-backend/assets/110277768/9fe78d2e-2e94-4072-be2e-a8ed1334c031">

위와 같은 불편함을 없애고 아래처럼 요청을 보낼 수 있도록 수정하고자 한다.
<img width="1013" alt="image" src="https://github.com/TAVE-balak/OTTify-backend/assets/110277768/589bf2c1-3829-4544-95f0-21a8b210606e">

#### 2. 프로필 수정 시 닉네임은 필수 -> 선택으로 변경
이 경우 프론트에서 무조건 기존 닉네임을 보내줘야 하므로 선택으로 변경하는 게 더 나을 것 같다고 판단했습니다.

#### 3. 프론트 측 연동 이슈로 @ModelAttribute() -> @RequestParam()과 @RequestPart() 사용으로 변경
닉네임만 변경하는 로직이 수행되지 않는 이슈가 있어서 어노테이션을 바꿔 다르게 구현해 봅니다.

## ✅ TODO
- [x]   프로필 수정 시 프로필 사진 필수 여부 체크에 대한 로직 변경
- [x] 프로필 수정 시 닉네임은 필수 -> 선택으로 변경
- [x] @ModelAttribute() -> @RequestParam()과 @RequestPart() 사용으로 변경
