### ISSUE TITLE
[API V1][프로그램] 검색,트렌딩 조회시 DB 저장 및 내용 반환

### ISSUE THREAD

**Issue by dionisos198** [TAVE-balak/OTTify-backend#14]
## 🔥 Issue
사용자가 검색 기능을 사용하거나 main 페이지에서 트렌딩을 통해  프로그램의 정보를 보여주고,
이 과정에서 DB에 저장되어 있지 않은 프로그램이라면 DB에 저장합니다.

## ✅ TODO
- [x]  검색 기능 사용시 프로그램 DB 저장
- [x]  검색 기능 사용시 관련 프로그램 보여주기
- [x]  트렌딩 요청 시 프로그램 DB 저장
- [x]  트렌딩 요청 시 관련 프로그램 보여주기
- [ ] 코드 리팩토링
