### ISSUE TITLE
[API V1][마이페이지] 프로그램 삭제 API 구현

### ISSUE THREAD

**Issue by jyjyjy25** [TAVE-balak/OTTify-backend#22]
## 🔥 Issue
프로그램 삭제와 관련된 API를 구현한다.

## ✅ TODO
- [x] 보고싶은 프로그램 삭제 API
- [x] 관심없는 프로그램 삭제 API
- [ ] 테스트 코드 작성

**Comment by jyjyjy25** [comment]
마이페이지에서 보고싶은/관심없는 프로그램 삭제 기능이 사라져서 해당 이슈를 close합니다.
