### ISSUE TITLE
[API V1][메인 요소] 최신 리뷰 한줄평

### ISSUE THREAD

**Issue by songhee1** [TAVE-balak/OTTify-backend#4]
## 🔥 Issue
- 메인 요소 중 최신 리뷰 한줄평 조회, 공감 적용, 해제 API 이슈입니다

## ✅ TODO
- [x]  서비스 메서드 작성
- [x]  공감 적용 서비스 작성
- [x]  공감 해제 서비스 작성
- [x]  발생하는 예외 리스트 작성
- [x]  리펙토링
- [x]  테스트 코드 작성
