### ISSUE TITLE
[API V1][토론, 메인페이지] API 로직 수정

### ISSUE THREAD

**Issue by songhee1** [TAVE-balak/OTTify-backend#42]
## 🔥 Issue
구현된 토론페이지와 메인페이지의 API 로직을 개선한다.

## ✅ TODO
- [x]  DTO를 request, reponse 폴더로 분리
- [x]  추천로직을 Random 이용해 작성
- [x]  Build로 인해 발생하는 deprecated 로직 수정
