### ISSUE TITLE
[API V1][메인 요소] 같은 취향을 가진 유저가 좋아하는 프로그램 추천 조회

### ISSUE THREAD

**Issue by songhee1** [TAVE-balak/OTTify-backend#5]
## 🔥 Issue
메인 요소 중 같은 취향을 가진 유저가 좋아하는 프로그램 추천 조회 API 이슈입니다

## ✅ TODO
- [x]  서비스 메서드 작성
- [x]   1순위 무작위, 2순위 무작위, 찜, 별점 기반 무작위 조회 메서드 작성 
- [x]  발생하는 예외 리스트 작성
- [x]  리펙토링
- [x]  테스트 코드 작성
