### ISSUE TITLE
[API V1] 프로젝트 배포 CI CD 관련 

### ISSUE THREAD

**Issue by dionisos198** [TAVE-balak/OTTify-backend#51]
## 🔥 Issue
CI CD 관련 세팅을 진행합니다.

## ✅ TODO
- [x]  ./github/workflows/cicd.yml 파일 작성
- [x] appspec.yml 파일 작성
- [x] scripts/deploy.sh 파일 작성
