### ISSUE TITLE
[API V1][SWAGGER] 스웨거 세팅 및 리뷰 태그 보완

### ISSUE THREAD

**Issue by dionisos198** [TAVE-balak/OTTify-backend#54]
## 🔥 Issue
기존에 구현했던 
메인 페이지에서 프로그램 보여주는 부분, 검색 페이지에서 프로그램 보여주는 부분, 상세페이지에서의 Entity 관련 기능의 SWAGGER를 세팅하고

프로그램 실행시 ReviewTag를 계속 저장하는 부분을 보완한다. 

## ✅ TODO
- [x]  메인 페이지 프로그램 관련 스웨거 세팅
- [x]  검색 페이지 프로그램 관련 스웨거 세팅
- [x]  상세 페이지 프로그램 Entity 관련 기능 SWAGGER 세팅 
- [x] 리뷰 태그 저장하는 부분 보완
