### ISSUE TITLE
[API V1][토론 페이지] API 보완

### ISSUE THREAD

**Issue by songhee1** [TAVE-balak/OTTify-backend#55]
## 🔥 Issue
배포 애플리케이션에서 에러가 난 토론페이지 생성 API와 DTO를 수정한다.

## ✅ TODO
- [x] 토론페이지 생성 API 중 멀티파트 파일 관련 어노테이션 수정
- [x] 생성 API DTO를 프로그램 id만 받는 것으로 수정
- [x] 변경된 API에 대해 테스트 파일 수정
