### ISSUE TITLE
[API V1][상세페이지] 인물 정보 가져오는 내용 및 OTT 정보 에러 관련  수정 

### ISSUE THREAD

**Issue by dionisos198** [TAVE-balak/OTTify-backend#79]
## 🔥 Issue
인물 정보 가져올 시 crew 를 제외한 cast 만 가지고 온다
또한 감독과 배우만 가져오는 것으로 수정하고 
OTT 에서 버그가 나는 부분도 리팩토링한다. 

## ✅ TODO
- [x]  crew 중에는 감독만 가지고 온다. 
- [x]  cast 에 감독과 배우만  가지고 온다. 
- [x]  일부 프로그램의 OTT null 문제를 해결한다.
- [x]  DTO 를 필요없는 부분은 반환하지 않도록 수정한다.
